# Generated by Django 3.0.7 on 2021-08-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20210808_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_model2',
            old_name='stock',
            new_name='stock3',
        ),
    ]
